[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/privacy"
  to   = "/privacy.html"
  status = 200

[[redirects]]
  from = "/compliance-report"
  to   = "/compliance-report.html"
  status = 200
